### PR TITLE
Make OnceCell not a struct tuple

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by nox** [comment]
@aelita-mergebot r+

**Comment by ghost** [comment]
:+1: [Build succeeded](https://travis-ci.org/nox/mitochondria/builds/177422048)

**Comment by notriddle** [comment]
I admit, I'm curious:

Why? What advantage do you get using a `value` field instead of a tuple struct?

**Comment by nox** [comment]
@notriddle A tuple struct always leaks its arity, and allows you to do `Foo(_)`, which would fail to compile if another field is added.

**Comment by notriddle** [comment]
Okay, that makes sense. Should you have released this as a breaking release instead of a patch release, then?

**Comment by nox** [comment]
@notriddle I would have if people did `Foo(_)`, but I don't even have a user hah.

**Pull request merged**
