### PR TITLE
Complete and fix the documentation of OnceCell

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by nox** [comment]
@aelita-mergebot r+

**Comment by ghost** [comment]
:+1: [Build succeeded](https://travis-ci.org/nox/mitochondria/builds/168070632)

**Comment by ghost** [comment]
:scream: Internal error while fast-forward master

**Comment by nox** [comment]
@notriddle ^ :(

**Comment by nox** [comment]
@aelita-mergebot r+

**Comment by ghost** [comment]
:+1: [Build succeeded](https://travis-ci.org/nox/mitochondria/builds/168071698)

**Pull request merged**
