### PR TITLE
Add feature 'no_std'

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by nox** [comment]
@aelita-mergebot r+

**Comment by ghost** [comment]
:+1: [Build succeeded](https://travis-ci.org/nox/mitochondria/builds/168011149)

**Comment by ghost** [comment]
:scream: Internal error while fast-forward master

**Comment by nox** [comment]
@aelita-mergebot r+

**Comment by ghost** [comment]
:+1: [Build succeeded](https://travis-ci.org/nox/mitochondria/builds/168011390)

**Comment by ghost** [comment]
:scream: Internal error while fast-forward master

**Comment by nox** [comment]
@aelita-mergebot r+

**Comment by ghost** [comment]
:+1: [Build succeeded](https://travis-ci.org/nox/mitochondria/builds/168011714)

**Pull request merged**
